import { describe, expect, it } from 'vitest'

import type { Report } from '../types.js'

import { renderHtml } from './html.js'

describe('renderHtml', () => {
  const mockReport: Report = {
    report_version: '1.0',
    timestamp: '2025-01-13T12:00:00.000Z',
    tool_version: '0.3.2',
    project_name: 'test-project',
    project_version: '1.0.0',
    global_packages: [
      {
        name: '@yabasha/gex',
        version: '0.3.2',
        resolved_path: '/usr/local/lib/node_modules/@yabasha/gex',
      },
    ],
    local_dependencies: [
      {
        name: 'axios',
        version: '1.6.0',
        resolved_path: '/path/to/project/node_modules/axios',
      },
    ],
    local_dev_dependencies: [
      {
        name: 'vitest',
        version: '2.1.9',
        resolved_path: '/path/to/project/node_modules/vitest',
      },
    ],
  }

  it('should render HTML with proper structure', () => {
    const result = renderHtml(mockReport)

    expect(result).toContain('<!DOCTYPE html>')
    expect(result).toContain('<html lang="en">')
    expect(result).toContain('<title>GEX Report - test-project</title>')
    expect(result).toContain('<h1>GEX Dependency Report</h1>')
    expect(result).toContain('Generated by <strong>GEX v0.3.2</strong>')
    expect(result).toContain('Report format version: 1.0')
  })

  it('should render project metadata', () => {
    const result = renderHtml({
      ...mockReport,
      project_description: 'Test project',
      project_homepage: 'https://example.com',
    })

    expect(result).toContain('<h2>Project Information</h2>')
    expect(result).toContain('Project Name</dt><dd>test-project</dd>')
    expect(result).toContain('Version</dt><dd>1.0.0</dd>')
    expect(result).toContain('Description</dt><dd>Test project</dd>')
    expect(result).toContain('Homepage</dt><dd><a href="https://example.com"')
  })

  it('should render package tables', () => {
    const result = renderHtml(mockReport)

    expect(result).toContain('<h2>Global Packages <small>(1)</small></h2>')
    expect(result).toContain('<h2>Local Dependencies <small>(1)</small></h2>')
    expect(result).toContain('<h2>Local Dev Dependencies <small>(1)</small></h2>')
    expect(result).toContain('axios</td>')
    expect(result).toContain('vitest</td>')
    expect(result).toContain('@yabasha/gex</td>')
  })

  it('should handle empty sections', () => {
    const emptyReport: Report = {
      report_version: '1.0',
      timestamp: '2025-01-13T12:00:00.000Z',
      tool_version: '0.3.2',
      global_packages: [],
      local_dependencies: [],
      local_dev_dependencies: [],
    }

    const result = renderHtml(emptyReport)

    expect(result).toContain(
      '<h2>Global Packages</h2><div class="no-data">No global packages found</div>',
    )
    expect(result).toContain(
      '<h2>Local Dependencies</h2><div class="no-data">No local dependencies found</div>',
    )
    expect(result).toContain(
      '<h2>Local Dev Dependencies</h2><div class="no-data">No local dev dependencies found</div>',
    )
  })

  it('should escape HTML entities', () => {
    const reportWithSpecialChars: Report = {
      report_version: '1.0',
      timestamp: '2025-01-13T12:00:00.000Z',
      tool_version: '0.3.2',
      global_packages: [
        {
          name: '<script>alert("xss")</script>',
          version: '1.0.0',
          resolved_path: '/path/<>&"',
        },
      ],
      local_dependencies: [],
      local_dev_dependencies: [],
    }

    const result = renderHtml(reportWithSpecialChars)

    expect(result).toContain('&lt;script&gt;alert(&quot;xss&quot;)&lt;/script&gt;</td>')
    expect(result).toContain('/path/&lt;&gt;&amp;&quot;</td>')
  })
})
