import { describe, it, expect } from 'vitest'

import type { Report } from '../types.js'

import { renderMarkdown } from './md.js'

describe('renderMarkdown', () => {
  it('renders sections and tables', () => {
    const rpt: Report = {
      report_version: '1.0',
      timestamp: new Date().toISOString(),
      tool_version: '0.1.0',
      project_name: 'demo',
      project_version: '0.0.1',
      global_packages: [],
      local_dependencies: [{ name: 'commander', version: '12.1.0', resolved_path: '/x' }],
      local_dev_dependencies: [{ name: 'vitest', version: '2.1.1', resolved_path: '/y' }],
    }

    const md = renderMarkdown({
      ...rpt,
      project_description: 'desc',
      project_homepage: 'https://x',
      project_bugs: 'https://x/issues',
    })
    expect(md).toContain('# GEX Report')
    expect(md).toContain('## Project Metadata')
    expect(md).toContain('## Local Dependencies')
    expect(md).toContain('| commander | 12.1.0 | /x |')
    expect(md).toContain('## Local Dev Dependencies')
    expect(md).toContain('| vitest | 2.1.1 | /y |')
    expect(md).toContain('_Generated by GEX_')
  })
})
