import { describe, expect, it } from 'vitest'

import { parseMarkdownReport } from './parser.js'

describe('parseMarkdownReport', () => {
  it('parses a 3-column report with Name | Version | Path', () => {
    const md = [
      '# GEX Report',
      '',
      '## Local Dependencies',
      '| Name | Version | Path |',
      '| --- | --- | --- |',
      '| axios | 1.6.0 | /path/to/axios |',
      '| commander | 12.1.0 | /path/to/commander |',
      '',
      '---',
      '_Generated by GEX_',
    ].join('\n')

    const report = parseMarkdownReport(md)
    expect(report.local_dependencies).toEqual([
      { name: 'axios', version: '1.6.0', resolved_path: '/path/to/axios' },
      { name: 'commander', version: '12.1.0', resolved_path: '/path/to/commander' },
    ])
    expect(report.local_dependencies[0]).not.toHaveProperty('deprecated')
  })

  it('preserves the Deprecated column on round-trips', () => {
    const md = [
      '# GEX Report',
      '',
      '## Local Dependencies',
      '| Name | Version | Path | Deprecated |',
      '| --- | --- | --- | --- |',
      '| request | 2.88.2 | /path/to/request | ⚠ request has been deprecated |',
      '| lodash | 4.17.21 | /path/to/lodash |  |',
      '',
      '---',
      '_Generated by GEX_',
    ].join('\n')

    const report = parseMarkdownReport(md)
    expect(report.local_dependencies).toEqual([
      {
        name: 'request',
        version: '2.88.2',
        resolved_path: '/path/to/request',
        deprecated: 'request has been deprecated',
      },
      {
        name: 'lodash',
        version: '4.17.21',
        resolved_path: '/path/to/lodash',
        deprecated: null,
      },
    ])
  })

  it('handles columns reordered relative to the renderer default', () => {
    const md = [
      '# GEX Report',
      '',
      '## Global Packages',
      '| Version | Name | Path |',
      '| --- | --- | --- |',
      '| 10.2.0 | npm | /usr/local/lib/node_modules/npm |',
      '',
      '---',
      '_Generated by GEX_',
    ].join('\n')

    const report = parseMarkdownReport(md)
    expect(report.global_packages).toEqual([
      { name: 'npm', version: '10.2.0', resolved_path: '/usr/local/lib/node_modules/npm' },
    ])
  })
})
